# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b11e3d67233995c8163205d9c69fd07d4b376f5dd00ef2ec4acd251c17d7e76beda36f6a1cc3011e647fe8b496f61f921177bbda22274b607b0fe4983724df82

test:
  secret_key_base: 3efd8ce127f01dafdafef5cc5c5e840ace031c97e192f4f81be376b543dadc976158b4a5ba9c14bb9fae49c96722cbdfbdd66aa2b2fbf92f096af45eaf33f820

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
